version: 2
  target-branch: "dev"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
